---
- name: Hello Events
  hosts: all
  sources:
    - benthomasson.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i == 1
      action:
        run_playbook:
          name: benthomasson.eda.hello
...
