---
- name: Hello Controller
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "Run job template"
      condition: event.i == 1
      action:
        run_job_template:
          name: eda-test-template
          organization: BTS Unix
          retries: 1
          delay: 10
...
